name: ci

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Build and Push'
      run: |
        docker build . --tag ghcr.io/swif2er/go-store-things:latest
        docker push ghcr.io/swif2er/go-store-things:latest
        
